### ISSUE TITLE
Secret Token does not survive page reload

### ISSUE THREAD

**Issue by nunovieira** [prisma/prisma-admin-feedback#100]
Looks like Prisma Admin does not save the Secret Token properly. 
After setting the Secret Token, when I reload the page, it shows the message `Connection unsucsessful, Incorrect access token provided.`.

Prisma Server 1.29.1

**Comment by Huvik** [comment]
This is implemented in latest release 🚀

**Comment by nunovieira** [comment]
Is that in the latest stable or beta or alpha?

**Comment by Huvik** [comment]
It should be everywhere right now :)
