### ISSUE TITLE
Prisma Admin not reflecting the changes after prisma deploy

### ISSUE THREAD

**Issue by danielsimao** [prisma/prisma-admin-feedback#105]
Hi,
I just added two new fields to my datamodel.prisma. Deployed it and had the following error:

`Applying changes 2.4s
 !    The Migration failed and has not been performed. This is very likely not a transient issue.
 !    java.lang.RuntimeException: MigrationValue method should only be called on scalar fields.
 !    at scala.sys.package$.error(package.scala:26)
 !    at
 !    com.prisma.deploy.connector.MigrationValueGenerator.migrationValueForField(MigrationValueGenerator.scala:18) !    at
 !    com.prisma.deploy.connector.MigrationValueGenerator.migrationValueForField$(MigrationValueGenerator.scala:9) !    at
 !    com.prisma.deploy.connector.mysql.database.MySqlJdbcDeployDatabaseMutationBuilder.migrationValueForField(MysqlJdbcDeployDatabaseMutationBuilder.scala:20)
 !    at
 !    com.prisma.deploy.connector.mysql.database.MySqlJdbcDeployDatabaseMutationBuilder.createColumn(MysqlJdbcDeployDatabaseMutationBuilder.scala:173)
 !    at
 !    com.prisma.deploy.connector.jdbc.database.CreateColumnHelper$.withIndexIfNecessary(ColumnMutactionInterpreters.scala:156)
 !    at
 !    com.prisma.deploy.connector.jdbc.database.CreateColumnInterpreter.execute(ColumnMutactionInterpreters.scala:14)
 !    at
 !    com.prisma.deploy.connector.jdbc.database.JdbcDeployMutactionExecutor.execute(JdbcDeployMutactionExecutor.scala:41)
 !    at
 !    com.prisma.deploy.migration.migrator.MigrationApplierImpl.executeClientMutaction(MigrationApplier.scala:119) !    at
 !    com.prisma.deploy.migration.migrator.MigrationApplierImpl.$anonfun$applyStep$2(MigrationApplier.scala:106)
 !    at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
 !    at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
 !    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
 !    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
 !    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
 !    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 !    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
 !    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
 !    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
 !    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
 !    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 !    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 !    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 !    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
 !

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ export DEBUG="*"`

I made sure the database was empty and after some tentatives, I managed to deploy it with no errors.

The problem now is that Prisma Admin Playground is not reflecting the changes I deployed even tho it is logged in the Deployment History.

**Comment by nunovieira** [comment]
I don't have that deployment error, but still Prisma Admin doesn't reflect changes to the data model.
Looks like Prisma Admin saves the queries on the browser's local storage, and it's not updated with `prisma deploy`.

**Comment by danielsimao** [comment]
> I don't have that deployment error, but still Prisma Admin doesn't reflect changes to the data model.
> Looks like Prisma Admin saves the queries on the browser's local storage, and it's not updated with `prisma deploy`.

I meant that the playground you can access through prisma admin, is reflecting the changes I make to the datamodel.

**Comment by nunovieira** [comment]
Do you mean Prisma's GraphQL Playground (http://localhost:4466/) or Prisma Admin (http://localhost:4466/_admin)?

**Comment by danielsimao** [comment]
`type Project  {
  id: ID! @unique
  name: String! @unique
  gitHubId: String! @unique
  url: String!
}`

I have found the problem. For some reason prisma deploy didn't allow me to have gitHubId as an ID, so I just changed it to a String? Do you know why can't it be an ID?

**Comment by Huvik** [comment]
This is implemented in latest release 🚀
