### ISSUE TITLE
Fields named "type" don't show in the Detail Area

### ISSUE THREAD

**Issue by nunovieira** [prisma/prisma-admin-feedback#117]
<img width="1072" alt="Screenshot 2019-04-09 at 16 32 34" src="https://user-images.githubusercontent.com/5137161/55895830-deb2a000-5bb4-11e9-991b-07f57b3e50ab.png">

[Slack thread](https://prisma.slack.com/archives/CA491RJH0/p1554820935471400)

**Comment by madebysid** [comment]
Hey, this does indeed apply to a bunch of field names that we treat as "special". I'm going to close this in favour of #121 :)
