### ISSUE TITLE
Design needed: DateTime picker

### ISSUE THREAD

**Issue by Huvik** [prisma/prisma-admin-feedback#14]
Currently `date-picker` has nice time change for days, but there is missing input for time. Where user is forced to insert correct format. Questions are:
* Should it be full text? How to display validation and in what format to insert it.
* Should there be field for `hour`,`seconds` and `microseconds`? 
* Should ve display date string in ISO format? `2018-12-05T17:01:22.560Z`

**Comment by kuldar** [comment]
I think we should follow the Graphcool datepicker behaviour for this one.
![datepicker](https://user-images.githubusercontent.com/1710629/49581552-96f3e180-f952-11e8-83fa-2b5269c950a8.gif)
