### ISSUE TITLE
Primary button could be more eye catchy

### ISSUE THREAD

**Issue by morajabi** [prisma/prisma-admin-feedback#2]
This is a nitpick visual/UX feedback, you can ignore it! 

![image](https://user-images.githubusercontent.com/12202757/48699827-a27ba480-ebff-11e8-98b0-41edb06b4352.png)

**Comment by timsuchanek** [comment]
Thanks for reporting! This has been addressed in the latest version.

![image](https://user-images.githubusercontent.com/1094804/50764969-bb561d00-1274-11e9-9b6c-c5a035508122.png)

**Comment by morajabi** [comment]
Looks great!
