### ISSUE TITLE
Feedback on initial "login" screen

### ISSUE THREAD

**Issue by DevanB** [prisma/prisma-admin-feedback#21]
I have a few tidbits about the first screen one sees when using Prisma Admin:

1. It took me nearly an hour to figure out the correct value to put in the "Endpoint Token" field. I didn’t realize it needed to be an actual authorization bearer token untill I inspected the network requests. Then I had to figure out how to generate that. A tooltip to provide a bit more detail on this field might helps others in the future.

2. There were many times when I was looking for a “logout” feature, to go back to the endpoint selection screen to change servers. I ultimately decided to refresh the page.

3. Not being able to edit the service endpoint once it’s saved caused me to remove and re-add service endpoints _a lot_.

Hope these help 😄

**Comment by Huvik** [comment]
I think we implemented everything in the new version! Thanks for your feedback! 🚀
