### ISSUE TITLE
Discuss: Rename the button to "rerun" if query hasn't changed

### ISSUE THREAD

**Issue by morajabi** [prisma/prisma-admin-feedback#3]
Because as soon as I open a query, I want to perform an action in my app, and see the result here. If I'm not changing the query and I want to "Run" again, it's probably known as "reload" or "rerun" in apps.

I also edited the "Show" button to "Edit", but I'm not sure about it, it's a suggestion to be discussed.

![image](https://user-images.githubusercontent.com/12202757/48700036-32215300-ec00-11e8-82bf-0d605de980c4.png)

**Comment by schickling** [comment]
Maybe instead "Re-run" with a refresh icon instead of the play icon? `🔃Re-run`
