### ISSUE TITLE
ID field in edit form causes crash

### ISSUE THREAD

**Issue by joserocha3** [prisma/prisma-admin-feedback#36]
I have a `User` type that has fields `updatedBy` and `createdBy` where we store an ID that points back to another `User`. It does not have a relation, our requirement is simply to contain the `ID`.

```graphql
type User {
  id: ID! @unique
  email: String! @unique  
  firstName: String!
  lastName: String!
  createdAt: DateTime!
  createdBy: ID
  updatedAt: DateTime!
  updatedBy: ID
}
```
When I try to edit that value the page crashes when I click on the field.

![screen shot 2019-01-04 at 12 11 12 pm](https://user-images.githubusercontent.com/11415340/50703475-d9741100-1019-11e9-8939-432e265d6f1e.png)

On click the entire screen turns white and the following shows up in Chrome developer console.

![screen shot 2019-01-04 at 12 11 51 pm](https://user-images.githubusercontent.com/11415340/50703515-fd375700-1019-11e9-9d0b-590c555ef497.png)

I have to refresh the page to get the admin console to display again.

Please let me know if any other details are required.

**Comment by Huvik** [comment]
@joserocha3 Thanks for reporting that :) Its fixed in new version.
