### ISSUE TITLE
New Onboarding View

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-admin-feedback#38]
- [x] Explain tokens
- [x] Add Databases (Mongo and Postgres)
- [x] Error states for Forms https://github.com/prisma/prisma-admin-feedback/issues/32
### Postgres
- host
- user
- password
- database
- schema
OR
- connection string
### Mongo
- Connection String
- Database name where the data is located

**Comment by kuldar** [comment]
Updated flow for onboarding now supports selecting between a Prisma service and a database to connect to. 

- The two types of projects are differenciated in the list by an icon.
- The design also includes example of an field error.
- The secret token field now also has a help link that would point to some docs/gist/explanation of what's needed.
- As per Johanneses suggestion, we left out the connection string option for PostgreSQL to simplify the UI.

### Adding a new project
![new-project](https://user-images.githubusercontent.com/1710629/51030635-595e2600-159a-11e9-934b-7b010375a4eb.gif)

### Editing an existing project
![edit-project](https://user-images.githubusercontent.com/1710629/51030647-611dca80-159a-11e9-95fc-219d50e16df2.gif)
