### ISSUE TITLE
JSON / Message for global Error Message

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-admin-feedback#40]

**Comment by kuldar** [comment]
The updated design for top error bar with a support for exposing the error JSON.
- Clicking on anywhere on the red bar (except the close button) should expand the error. (We might rethink if the "Show the error message" link makes sense. Currently added it to make the action bit more obvious)
- The white JSON error message box should have a `max-height` with `overflow:scroll`, to prevent from taking up the entire screen
- Clicking on the close button should close the error

### Folded
![general](https://user-images.githubusercontent.com/1710629/51035434-42273480-15aa-11e9-9f8d-a18cacbec50c.png)

### Expanded
![expanded](https://user-images.githubusercontent.com/1710629/51035437-42273480-15aa-11e9-97db-a3d7bf2fa5af.png)
