### ISSUE TITLE
Proper favicon & page title

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-admin-feedback#55]
We should come up with a better favicon and adjust the page title dynamically based on the current query name (e.g. `Users - Prisma Admin`).

**Comment by kuldar** [comment]
Should we use Prisma logo for favicon or do we need a separate logo for Admin as well?

**Comment by Huvik** [comment]
We are going to need an electron icon too.

**Comment by schickling** [comment]
@kuldar I think the Prisma logo should be a good starting point but could also imaging having a dedicated logo for it. Leaving it up to you.
