### ISSUE TITLE
Incorrect relations shown after switching queries

### ISSUE THREAD

**Issue by kuldar** [prisma/prisma-admin-feedback#56]
Just ran into this – it seems like the `posts` field is showing incorrect relations when switching between `User` and `Post` queries. The data is correct on page-load, but changes after looking at another query.

![admin-bug-1](https://user-images.githubusercontent.com/1710629/51392449-5385b900-1b35-11e9-941e-5820177826d2.gif)

**Comment by juliansthl** [comment]
I'm experiencing the same issue whenever I switch between Queries and don't hit the rerun button

![feb-08-2019 11-33-46](https://user-images.githubusercontent.com/7814840/52473270-a59a8700-2b95-11e9-9ae3-77c8b0d1a753.gif)
