### ISSUE TITLE
Focus "Save to Database" button when change has been made to allow for "double enter" to apply changes

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-admin-feedback#64]
When I want to make some changes to my data quickly (e.g. using inline editing) it should be possible to hit the enter button twice to actually save the changes to the database. The best way to implement this is by automatically have the browser focus the "Save to Database" button.

**Comment by kuldar** [comment]
An alternative approach would maybe have a `cmd+return` or something similar for the "Run" command. Otherwise I can see cases where you have to fight against the autofocus when navigating around the table and making changes.

**Comment by Huvik** [comment]
Kuldar added a shortcut for save to database in #23.
