### ISSUE TITLE
Relation modal doesn't allow selecting entries

### ISSUE THREAD

**Issue by juliansthl** [prisma/prisma-admin-feedback#72]
When opening the modal for a relation field, it says that one entry is connected (which is correct) although none of the checkboxes is selected (which should not be the case).

When clicking on a checkbox it does not get selected so it is also not possible to select multiple items.

![kapture 2019-02-08 at 12 11 48](https://user-images.githubusercontent.com/7814840/52475147-e052ee00-2b9a-11e9-89b3-298e72a5406d.gif)

**Comment by Huvik** [comment]
This should be fixed, thanks for reporting!
