### ISSUE TITLE
Not all required records are showing up as required in Prisma Admin 

### ISSUE THREAD

**Issue by etelsv** [prisma/prisma-admin-feedback#74]
There are fields that show up as required in my data model that don't like like they are in Prisma admin. This leads me to not be able to add a record when I think I should because I didn't know the fields wre required. Below is my data model and attached is the form version that Admin shows. Votes and cuisine in my case don't seem to be required. 

```
type Restaurant {
  id: ID! @unique
  name: String! @unique
  cuisine: Cuisine!
  votes: [Vote!]!
  bracketLocation: Int!
}

type Vote {
  id: ID! @unique
  createdAt: DateTime!
  voter: String!
  token: String!
  restaurant: Restaurant!
}

type Cuisine {
  id: ID! @unique
  name: String!
}
```

<img width="285" alt="screenshot 2019-02-26 at 18 40 25" src="https://user-images.githubusercontent.com/42931286/53434050-092a0e80-39f6-11e9-8ae6-31a88a23ef99.png">

**Comment by Huvik** [comment]
Thanks for reporting! It should be fixed 🚀
