### ISSUE TITLE
After running a query to only show the first three results, I cannot see the full list

### ISSUE THREAD

**Issue by etelsv** [prisma/prisma-admin-feedback#78]
The full list of results is no longer reachable after I ran a query to just see the first three. 

After running this query:

```
{
  posts(first: 3) {
    id
    title
    published
    author {
      id
    }
    comments {
      id
    }
  }
}
```

I see the following results when I want to see all of the entries 
<img width="1393" alt="Screenshot 2019-03-12 at 16 25 12" src="https://user-images.githubusercontent.com/42931286/54212629-8455ef00-44e3-11e9-9733-f13de501147e.png">

Rerunning the query doesn't work, but refreshing the page seems to mitigate the issue.

**Comment by Huvik** [comment]
It's fixed now 🚀
