### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getRegistrations' of undefined

### ISSUE THREAD

**Issue by LawJolla** [prisma/prisma-admin-feedback#79]
Version: 1.29-beta
Environment:  AWS/Fargate

Problem:
Visiting `http://...aws.com/wk/dev/_admin` gives a white screen with console errors:

`Uncaught TypeError: Cannot read property 'getRegistrations' of undefined`
and
`Uncaught ReferenceError: PrismaAdmin is not defined`

![Image 2019-03-13 at 3 06 49 PM](https://user-images.githubusercontent.com/17485128/54317894-c9d8f180-45a1-11e9-96f7-22a01270abf5.png)

Same error when launching from `prisma admin` in the console.

Please let me know how I can be more specific!

**Comment by Huvik** [comment]
This is fixed in the latest release, sorry for troubles 🚀
