### ISSUE TITLE
Create -> Connect Nodes is broken

### ISSUE THREAD

**Issue by thecodelayeriser** [prisma/prisma-admin-feedback#86]
Anyone who is experiencing not being able to connect nodes with the new Prisma Admin? Clicking on connect -> hereafter selecting a node  -> Save Changes = node not connected.

<img width="293" alt="Screenshot 2019-03-14 at 17 01 04" src="https://user-images.githubusercontent.com/41742232/54373686-011cd080-467e-11e9-9ba6-62918d435661.png">

Video: https://slack-files.com/T0MQBS8JG-FH04S5X5M-ea69f8a8a3

**Comment by Huvik** [comment]
This is fixed in latest release, sorry for troubles 🚀
