### ISSUE TITLE
Not all Tables are showing

### ISSUE THREAD

**Issue by quinnvaughn** [prisma/prisma-admin-feedback#95]
About half of my tables aren't showing up in the left hand column. They're available in playground, however.

**Comment by divyenduz** [comment]
The way admin works is by writing queries for the known tables that are visible in the left hand side. This is not however applied for changes in the datamodel. 

We will fix this shortly and playground will sync with the underlying structure.

**Comment by Huvik** [comment]
Closing in favor of #87
